steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/plasma-matter-430405-d9/cicd-gke/app1-image:v1', './app1' ]
  id: 'Build Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/plasma-matter-430405-d9/cicd-gke/app1-image:v1' ]
  id: 'Push Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/plasma-matter-430405-d9/cicd-gke/app2-image:v1', './app2' ]
  id: 'Build Docker Image2'


- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/plasma-matter-430405-d9/cicd-gke/app2-image:v1' ]
  id: 'Push Docker Image2'


- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |   
    #gcloud deploy apply --file pipeline.yaml --region=us-central1
    gcloud deploy apply --file dev.yaml --region=us-central1
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=cicid-app-deploy --region=us-central1 --from-k8s-manifest=./k8s/app1.yaml
    # gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=cicid-app-deploy --region=us-central1 --from-k8s-manifest=./k8s/app2.yaml
    # --skaffold-file=skaffold.yaml


options:
  logging: CLOUD_LOGGING_ONLY    
