apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cicid-app-deploy
  labels:
    app: cicd
description: cicd delivery pipeline
serialPipeline:
  stages:
  - targetId: autopilot-dev-cluster
    # profiles:
    # - dev
  # - targetId: staging
  #   profiles:
  #   - staging
  - targetId: prod-cluster-1
  #   profiles:
  #   - prod
