apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: flask-container
          image: us-central1-docker.pkg.dev/plasma-matter-430405-d9/cicd-gke/app2-image:v1
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
